//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismTemplates.DalEF4
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeGenString
    {
        public int Id { get; set; }
        public string StringKey { get; set; }
        public string StringValue { get; set; }
        public string StringComment { get; set; }
        public string EMHStringName { get; set; }
        public bool ClientSide { get; set; }
    }
}
